version: '3'
services:
  db:
    build: 
        context: .
        dockerfile: Dockerfile.postgres
    networks:
        - mynet
    volumes:
        - postgres-data:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: Dockerfile.globar
    ports:
      - 8888:8888
    networks:
      - mynet
    environment:
      - PRODUCTION
networks:
    mynet:
        driver: bridge
volumes:
    postgres-data:
