version: '3'
services:
  db:
    build: 
        context: .
        dockerfile: Dockerfile.postgres
    networks:
        - mynet

  app:
    build: 
      context: .
      dockerfile: Dockerfile.globar
    ports:
      - 8888:8888
    networks:
      - mynet
networks:
    mynet:
        driver: bridge
